# Project: IPChanger
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Obj/IPChanger_private.res
OBJ  = Obj/IpChanger.o Obj/WinGUI.o Obj/Tools.o $(RES)
LINKOBJ  = Obj/IpChanger.o Obj/WinGUI.o Obj/Tools.o $(RES)
LIBS =  -L"C:/Users/Mietek/Downloads/Dev-Cpp/Dev-Cpp/lib" -mwindows -lcomctl32 -lversion -lpsapi -lwsock32 -lshlwapi -lxml2 -Wall -s  
INCS =  -I"C:/Users/Mietek/Downloads/Dev-Cpp/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/Mietek/Downloads/Dev-Cpp/Dev-Cpp/include" 
BIN  = IPChanger.exe
CXXFLAGS = $(CXXINCS) -D_WIN32_IE=0x0501 -D_WIN32_WINNT=0x0501  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before IPChanger.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "IPChanger.exe" $(LIBS)

Obj/IpChanger.o: ../IpChanger.cpp
	$(CPP) -c ../IpChanger.cpp -o Obj/IpChanger.o $(CXXFLAGS)

Obj/WinGUI.o: ../WinGUI.cpp
	$(CPP) -c ../WinGUI.cpp -o Obj/WinGUI.o $(CXXFLAGS)

Obj/Tools.o: ../Tools.cpp
	$(CPP) -c ../Tools.cpp -o Obj/Tools.o $(CXXFLAGS)

Obj/IPChanger_private.res: IPChanger_private.rc ../IpChanger.rc 
	$(WINDRES) -i IPChanger_private.rc --input-format=rc -o Obj/IPChanger_private.res -O coff 
